/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkspaceSlugRouteImport } from "./routes/$workspaceSlug"
import { Route as WorkspaceSlugIndexRouteImport } from "./routes/$workspaceSlug.index"
import { Route as WorkspaceSlugAgentsAgentIdRouteImport } from "./routes/$workspaceSlug.agents.$agentId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: "/$workspaceSlug",
  path: "/$workspaceSlug",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugAgentsAgentIdRoute =
  WorkspaceSlugAgentsAgentIdRouteImport.update({
    id: "/agents/$agentId",
    path: "/agents/$agentId",
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugRouteWithChildren
  "/$workspaceSlug/": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugRouteWithChildren
  "/$workspaceSlug/": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$workspaceSlug"
    | "/$workspaceSlug/"
    | "/$workspaceSlug/agents/$agentId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$workspaceSlug" | "/$workspaceSlug/agents/$agentId"
  id:
    | "__root__"
    | "/"
    | "/$workspaceSlug"
    | "/$workspaceSlug/"
    | "/$workspaceSlug/agents/$agentId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceSlug": {
      id: "/$workspaceSlug"
      path: "/$workspaceSlug"
      fullPath: "/$workspaceSlug"
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceSlug/": {
      id: "/$workspaceSlug/"
      path: "/"
      fullPath: "/$workspaceSlug/"
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    "/$workspaceSlug/agents/$agentId": {
      id: "/$workspaceSlug/agents/$agentId"
      path: "/agents/$agentId"
      fullPath: "/$workspaceSlug/agents/$agentId"
      preLoaderRoute: typeof WorkspaceSlugAgentsAgentIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
  }
}

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugAgentsAgentIdRoute: typeof WorkspaceSlugAgentsAgentIdRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugAgentsAgentIdRoute: WorkspaceSlugAgentsAgentIdRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
