/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkspaceSlugRouteImport } from "./routes/$workspaceSlug"
import { Route as WorkspaceSlugIndexRouteImport } from "./routes/$workspaceSlug.index"
import { Route as WorkspaceSlugSettingsRouteImport } from "./routes/$workspaceSlug.settings"
import { Route as WorkspaceSlugAgentsAgentIdRouteImport } from "./routes/$workspaceSlug.agents.$agentId"
import { Route as WorkspaceSlugSettingsIndexRouteImport } from "./routes/$workspaceSlug.settings.index"
import { Route as WorkspaceSlugSettingsAccountRouteImport } from "./routes/$workspaceSlug.settings.account"
import { Route as WorkspaceSlugSettingsConnectorsRouteImport } from "./routes/$workspaceSlug.settings.connectors"
import { Route as WorkspaceSlugSettingsMembersRouteImport } from "./routes/$workspaceSlug.settings.members"
import { Route as WorkspaceSlugSettingsProfileRouteImport } from "./routes/$workspaceSlug.settings.profile"
import { Route as WorkspaceSlugSettingsTeamsRouteImport } from "./routes/$workspaceSlug.settings.teams"
import { Route as WorkspaceSlugSettingsWorkspaceRouteImport } from "./routes/$workspaceSlug.settings.workspace"
import { Route as WorkspaceSlugSettingsConnectorsIndexRouteImport } from "./routes/$workspaceSlug.settings.connectors.index"
import { Route as WorkspaceSlugSettingsConnectorsConnectorIdRouteImport } from "./routes/$workspaceSlug.settings.connectors.$connectorId"
import { Route as WorkspaceSlugSettingsTeamsIndexRouteImport } from "./routes/$workspaceSlug.settings.teams.index"
import { Route as WorkspaceSlugSettingsTeamsTeamSlugRouteImport } from "./routes/$workspaceSlug.settings.teams.$teamSlug"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: "/$workspaceSlug",
  path: "/$workspaceSlug",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugAgentsAgentIdRoute =
  WorkspaceSlugAgentsAgentIdRouteImport.update({
    id: "/agents/$agentId",
    path: "/agents/$agentId",
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugSettingsIndexRoute =
  WorkspaceSlugSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsAccountRoute =
  WorkspaceSlugSettingsAccountRouteImport.update({
    id: "/account",
    path: "/account",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsConnectorsRoute =
  WorkspaceSlugSettingsConnectorsRouteImport.update({
    id: "/connectors",
    path: "/connectors",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsMembersRoute =
  WorkspaceSlugSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsProfileRoute =
  WorkspaceSlugSettingsProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsTeamsRoute =
  WorkspaceSlugSettingsTeamsRouteImport.update({
    id: "/teams",
    path: "/teams",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsWorkspaceRoute =
  WorkspaceSlugSettingsWorkspaceRouteImport.update({
    id: "/workspace",
    path: "/workspace",
    getParentRoute: () => WorkspaceSlugSettingsRoute,
  } as any)
const WorkspaceSlugSettingsConnectorsIndexRoute =
  WorkspaceSlugSettingsConnectorsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspaceSlugSettingsConnectorsRoute,
  } as any)
const WorkspaceSlugSettingsConnectorsConnectorIdRoute =
  WorkspaceSlugSettingsConnectorsConnectorIdRouteImport.update({
    id: "/$connectorId",
    path: "/$connectorId",
    getParentRoute: () => WorkspaceSlugSettingsConnectorsRoute,
  } as any)
const WorkspaceSlugSettingsTeamsIndexRoute =
  WorkspaceSlugSettingsTeamsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspaceSlugSettingsTeamsRoute,
  } as any)
const WorkspaceSlugSettingsTeamsTeamSlugRoute =
  WorkspaceSlugSettingsTeamsTeamSlugRouteImport.update({
    id: "/$teamSlug",
    path: "/$teamSlug",
    getParentRoute: () => WorkspaceSlugSettingsTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugRouteWithChildren
  "/$workspaceSlug/settings": typeof WorkspaceSlugSettingsRouteWithChildren
  "/$workspaceSlug/": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
  "/$workspaceSlug/settings/account": typeof WorkspaceSlugSettingsAccountRoute
  "/$workspaceSlug/settings/connectors": typeof WorkspaceSlugSettingsConnectorsRouteWithChildren
  "/$workspaceSlug/settings/members": typeof WorkspaceSlugSettingsMembersRoute
  "/$workspaceSlug/settings/profile": typeof WorkspaceSlugSettingsProfileRoute
  "/$workspaceSlug/settings/teams": typeof WorkspaceSlugSettingsTeamsRouteWithChildren
  "/$workspaceSlug/settings/workspace": typeof WorkspaceSlugSettingsWorkspaceRoute
  "/$workspaceSlug/settings/": typeof WorkspaceSlugSettingsIndexRoute
  "/$workspaceSlug/settings/connectors/$connectorId": typeof WorkspaceSlugSettingsConnectorsConnectorIdRoute
  "/$workspaceSlug/settings/teams/$teamSlug": typeof WorkspaceSlugSettingsTeamsTeamSlugRoute
  "/$workspaceSlug/settings/connectors/": typeof WorkspaceSlugSettingsConnectorsIndexRoute
  "/$workspaceSlug/settings/teams/": typeof WorkspaceSlugSettingsTeamsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
  "/$workspaceSlug/settings/account": typeof WorkspaceSlugSettingsAccountRoute
  "/$workspaceSlug/settings/members": typeof WorkspaceSlugSettingsMembersRoute
  "/$workspaceSlug/settings/profile": typeof WorkspaceSlugSettingsProfileRoute
  "/$workspaceSlug/settings/workspace": typeof WorkspaceSlugSettingsWorkspaceRoute
  "/$workspaceSlug/settings": typeof WorkspaceSlugSettingsIndexRoute
  "/$workspaceSlug/settings/connectors/$connectorId": typeof WorkspaceSlugSettingsConnectorsConnectorIdRoute
  "/$workspaceSlug/settings/teams/$teamSlug": typeof WorkspaceSlugSettingsTeamsTeamSlugRoute
  "/$workspaceSlug/settings/connectors": typeof WorkspaceSlugSettingsConnectorsIndexRoute
  "/$workspaceSlug/settings/teams": typeof WorkspaceSlugSettingsTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$workspaceSlug": typeof WorkspaceSlugRouteWithChildren
  "/$workspaceSlug/settings": typeof WorkspaceSlugSettingsRouteWithChildren
  "/$workspaceSlug/": typeof WorkspaceSlugIndexRoute
  "/$workspaceSlug/agents/$agentId": typeof WorkspaceSlugAgentsAgentIdRoute
  "/$workspaceSlug/settings/account": typeof WorkspaceSlugSettingsAccountRoute
  "/$workspaceSlug/settings/connectors": typeof WorkspaceSlugSettingsConnectorsRouteWithChildren
  "/$workspaceSlug/settings/members": typeof WorkspaceSlugSettingsMembersRoute
  "/$workspaceSlug/settings/profile": typeof WorkspaceSlugSettingsProfileRoute
  "/$workspaceSlug/settings/teams": typeof WorkspaceSlugSettingsTeamsRouteWithChildren
  "/$workspaceSlug/settings/workspace": typeof WorkspaceSlugSettingsWorkspaceRoute
  "/$workspaceSlug/settings/": typeof WorkspaceSlugSettingsIndexRoute
  "/$workspaceSlug/settings/connectors/$connectorId": typeof WorkspaceSlugSettingsConnectorsConnectorIdRoute
  "/$workspaceSlug/settings/teams/$teamSlug": typeof WorkspaceSlugSettingsTeamsTeamSlugRoute
  "/$workspaceSlug/settings/connectors/": typeof WorkspaceSlugSettingsConnectorsIndexRoute
  "/$workspaceSlug/settings/teams/": typeof WorkspaceSlugSettingsTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$workspaceSlug"
    | "/$workspaceSlug/settings"
    | "/$workspaceSlug/"
    | "/$workspaceSlug/agents/$agentId"
    | "/$workspaceSlug/settings/account"
    | "/$workspaceSlug/settings/connectors"
    | "/$workspaceSlug/settings/members"
    | "/$workspaceSlug/settings/profile"
    | "/$workspaceSlug/settings/teams"
    | "/$workspaceSlug/settings/workspace"
    | "/$workspaceSlug/settings/"
    | "/$workspaceSlug/settings/connectors/$connectorId"
    | "/$workspaceSlug/settings/teams/$teamSlug"
    | "/$workspaceSlug/settings/connectors/"
    | "/$workspaceSlug/settings/teams/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$workspaceSlug"
    | "/$workspaceSlug/agents/$agentId"
    | "/$workspaceSlug/settings/account"
    | "/$workspaceSlug/settings/members"
    | "/$workspaceSlug/settings/profile"
    | "/$workspaceSlug/settings/workspace"
    | "/$workspaceSlug/settings"
    | "/$workspaceSlug/settings/connectors/$connectorId"
    | "/$workspaceSlug/settings/teams/$teamSlug"
    | "/$workspaceSlug/settings/connectors"
    | "/$workspaceSlug/settings/teams"
  id:
    | "__root__"
    | "/"
    | "/$workspaceSlug"
    | "/$workspaceSlug/settings"
    | "/$workspaceSlug/"
    | "/$workspaceSlug/agents/$agentId"
    | "/$workspaceSlug/settings/account"
    | "/$workspaceSlug/settings/connectors"
    | "/$workspaceSlug/settings/members"
    | "/$workspaceSlug/settings/profile"
    | "/$workspaceSlug/settings/teams"
    | "/$workspaceSlug/settings/workspace"
    | "/$workspaceSlug/settings/"
    | "/$workspaceSlug/settings/connectors/$connectorId"
    | "/$workspaceSlug/settings/teams/$teamSlug"
    | "/$workspaceSlug/settings/connectors/"
    | "/$workspaceSlug/settings/teams/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceSlug": {
      id: "/$workspaceSlug"
      path: "/$workspaceSlug"
      fullPath: "/$workspaceSlug"
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$workspaceSlug/": {
      id: "/$workspaceSlug/"
      path: "/"
      fullPath: "/$workspaceSlug/"
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    "/$workspaceSlug/settings": {
      id: "/$workspaceSlug/settings"
      path: "/settings"
      fullPath: "/$workspaceSlug/settings"
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    "/$workspaceSlug/agents/$agentId": {
      id: "/$workspaceSlug/agents/$agentId"
      path: "/agents/$agentId"
      fullPath: "/$workspaceSlug/agents/$agentId"
      preLoaderRoute: typeof WorkspaceSlugAgentsAgentIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    "/$workspaceSlug/settings/": {
      id: "/$workspaceSlug/settings/"
      path: "/"
      fullPath: "/$workspaceSlug/settings/"
      preLoaderRoute: typeof WorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/account": {
      id: "/$workspaceSlug/settings/account"
      path: "/account"
      fullPath: "/$workspaceSlug/settings/account"
      preLoaderRoute: typeof WorkspaceSlugSettingsAccountRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/connectors": {
      id: "/$workspaceSlug/settings/connectors"
      path: "/connectors"
      fullPath: "/$workspaceSlug/settings/connectors"
      preLoaderRoute: typeof WorkspaceSlugSettingsConnectorsRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/members": {
      id: "/$workspaceSlug/settings/members"
      path: "/members"
      fullPath: "/$workspaceSlug/settings/members"
      preLoaderRoute: typeof WorkspaceSlugSettingsMembersRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/profile": {
      id: "/$workspaceSlug/settings/profile"
      path: "/profile"
      fullPath: "/$workspaceSlug/settings/profile"
      preLoaderRoute: typeof WorkspaceSlugSettingsProfileRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/teams": {
      id: "/$workspaceSlug/settings/teams"
      path: "/teams"
      fullPath: "/$workspaceSlug/settings/teams"
      preLoaderRoute: typeof WorkspaceSlugSettingsTeamsRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/workspace": {
      id: "/$workspaceSlug/settings/workspace"
      path: "/workspace"
      fullPath: "/$workspaceSlug/settings/workspace"
      preLoaderRoute: typeof WorkspaceSlugSettingsWorkspaceRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRoute
    }
    "/$workspaceSlug/settings/connectors/": {
      id: "/$workspaceSlug/settings/connectors/"
      path: "/"
      fullPath: "/$workspaceSlug/settings/connectors/"
      preLoaderRoute: typeof WorkspaceSlugSettingsConnectorsIndexRouteImport
      parentRoute: typeof WorkspaceSlugSettingsConnectorsRoute
    }
    "/$workspaceSlug/settings/connectors/$connectorId": {
      id: "/$workspaceSlug/settings/connectors/$connectorId"
      path: "/$connectorId"
      fullPath: "/$workspaceSlug/settings/connectors/$connectorId"
      preLoaderRoute: typeof WorkspaceSlugSettingsConnectorsConnectorIdRouteImport
      parentRoute: typeof WorkspaceSlugSettingsConnectorsRoute
    }
    "/$workspaceSlug/settings/teams/": {
      id: "/$workspaceSlug/settings/teams/"
      path: "/"
      fullPath: "/$workspaceSlug/settings/teams/"
      preLoaderRoute: typeof WorkspaceSlugSettingsTeamsIndexRouteImport
      parentRoute: typeof WorkspaceSlugSettingsTeamsRoute
    }
    "/$workspaceSlug/settings/teams/$teamSlug": {
      id: "/$workspaceSlug/settings/teams/$teamSlug"
      path: "/$teamSlug"
      fullPath: "/$workspaceSlug/settings/teams/$teamSlug"
      preLoaderRoute: typeof WorkspaceSlugSettingsTeamsTeamSlugRouteImport
      parentRoute: typeof WorkspaceSlugSettingsTeamsRoute
    }
  }
}

interface WorkspaceSlugSettingsConnectorsRouteChildren {
  WorkspaceSlugSettingsConnectorsConnectorIdRoute: typeof WorkspaceSlugSettingsConnectorsConnectorIdRoute
  WorkspaceSlugSettingsConnectorsIndexRoute: typeof WorkspaceSlugSettingsConnectorsIndexRoute
}

const WorkspaceSlugSettingsConnectorsRouteChildren: WorkspaceSlugSettingsConnectorsRouteChildren =
  {
    WorkspaceSlugSettingsConnectorsConnectorIdRoute:
      WorkspaceSlugSettingsConnectorsConnectorIdRoute,
    WorkspaceSlugSettingsConnectorsIndexRoute:
      WorkspaceSlugSettingsConnectorsIndexRoute,
  }

const WorkspaceSlugSettingsConnectorsRouteWithChildren =
  WorkspaceSlugSettingsConnectorsRoute._addFileChildren(
    WorkspaceSlugSettingsConnectorsRouteChildren,
  )

interface WorkspaceSlugSettingsTeamsRouteChildren {
  WorkspaceSlugSettingsTeamsTeamSlugRoute: typeof WorkspaceSlugSettingsTeamsTeamSlugRoute
  WorkspaceSlugSettingsTeamsIndexRoute: typeof WorkspaceSlugSettingsTeamsIndexRoute
}

const WorkspaceSlugSettingsTeamsRouteChildren: WorkspaceSlugSettingsTeamsRouteChildren =
  {
    WorkspaceSlugSettingsTeamsTeamSlugRoute:
      WorkspaceSlugSettingsTeamsTeamSlugRoute,
    WorkspaceSlugSettingsTeamsIndexRoute: WorkspaceSlugSettingsTeamsIndexRoute,
  }

const WorkspaceSlugSettingsTeamsRouteWithChildren =
  WorkspaceSlugSettingsTeamsRoute._addFileChildren(
    WorkspaceSlugSettingsTeamsRouteChildren,
  )

interface WorkspaceSlugSettingsRouteChildren {
  WorkspaceSlugSettingsAccountRoute: typeof WorkspaceSlugSettingsAccountRoute
  WorkspaceSlugSettingsConnectorsRoute: typeof WorkspaceSlugSettingsConnectorsRouteWithChildren
  WorkspaceSlugSettingsMembersRoute: typeof WorkspaceSlugSettingsMembersRoute
  WorkspaceSlugSettingsProfileRoute: typeof WorkspaceSlugSettingsProfileRoute
  WorkspaceSlugSettingsTeamsRoute: typeof WorkspaceSlugSettingsTeamsRouteWithChildren
  WorkspaceSlugSettingsWorkspaceRoute: typeof WorkspaceSlugSettingsWorkspaceRoute
  WorkspaceSlugSettingsIndexRoute: typeof WorkspaceSlugSettingsIndexRoute
}

const WorkspaceSlugSettingsRouteChildren: WorkspaceSlugSettingsRouteChildren = {
  WorkspaceSlugSettingsAccountRoute: WorkspaceSlugSettingsAccountRoute,
  WorkspaceSlugSettingsConnectorsRoute:
    WorkspaceSlugSettingsConnectorsRouteWithChildren,
  WorkspaceSlugSettingsMembersRoute: WorkspaceSlugSettingsMembersRoute,
  WorkspaceSlugSettingsProfileRoute: WorkspaceSlugSettingsProfileRoute,
  WorkspaceSlugSettingsTeamsRoute: WorkspaceSlugSettingsTeamsRouteWithChildren,
  WorkspaceSlugSettingsWorkspaceRoute: WorkspaceSlugSettingsWorkspaceRoute,
  WorkspaceSlugSettingsIndexRoute: WorkspaceSlugSettingsIndexRoute,
}

const WorkspaceSlugSettingsRouteWithChildren =
  WorkspaceSlugSettingsRoute._addFileChildren(
    WorkspaceSlugSettingsRouteChildren,
  )

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRouteWithChildren
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugAgentsAgentIdRoute: typeof WorkspaceSlugAgentsAgentIdRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRouteWithChildren,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugAgentsAgentIdRoute: WorkspaceSlugAgentsAgentIdRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
